version: "3.9"
services:
  rl_dev:
    container_name: ambf-ros-galactic
    build: .
    image: collaborativerobotics/ambf-ros:galactic
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: zsh
    env_file: env
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
